- menu_name: "Servicios"

- name: "Contacto"
  url: "/contact/"
  title: "Contacto"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribirse al feed RSS"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscribirse al feed Atom"

- name: "Sitemap"
  url: "/sitemap.xml"
  title: "Sitemap para Google Webmaster Tools"
